"""empty message

Revision ID: 19180554c5ad
Revises: 50b1e5696c6f
Create Date: 2020-07-14 19:50:05.337730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19180554c5ad'
down_revision = '50b1e5696c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('passowrd', sa.String(length=50), nullable=False),
    sa.Column('password_confirmation', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('site_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_data')
    # ### end Alembic commands ###
