"""empty message

Revision ID: b1f900f963bb
Revises: e0da90f54858
Create Date: 2020-07-14 16:05:35.971913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f900f963bb'
down_revision = 'e0da90f54858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('site_users', sa.Column('password', sa.String(length=50), nullable=True))
    op.add_column('site_users', sa.Column('password_confirmation', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_users', 'password_confirmation')
    op.drop_column('site_users', 'password')
    op.drop_column('site_users', 'email')
    # ### end Alembic commands ###
