"""empty message

Revision ID: c9449709014c
Revises: 19180554c5ad
Create Date: 2020-07-14 20:10:26.912352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9449709014c'
down_revision = '19180554c5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('password', sa.String(length=50), nullable=False))
    op.drop_column('user_data', 'passowrd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('passowrd', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('user_data', 'password')
    # ### end Alembic commands ###
