"""empty message

Revision ID: f0e887bc7edc
Revises: e0da90f54858
Create Date: 2020-07-14 19:38:52.258272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e887bc7edc'
down_revision = 'e0da90f54858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.NUMERIC(), nullable=True),
    sa.Column('email', sa.NUMERIC(), nullable=True),
    sa.Column('password', sa.NUMERIC(), nullable=True),
    sa.Column('password_confirmation', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['job_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('site_users')
    # ### end Alembic commands ###
